# Generated by Django 2.2.3 on 2019-10-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
    ]
