# Generated by Django 2.2.3 on 2019-10-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_blog_readed_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
