# Generated by Django 2.2.3 on 2020-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20200112_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
