# Generated by Django 2.2.3 on 2020-03-05 12:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/%Y%m%d'),
        ),
    ]
