# Generated by Django 2.2.3 on 2020-03-05 15:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/upload/%Y%m%d'),
        ),
    ]
