# Generated by Django 2.2.3 on 2020-03-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_blog_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='avatar',
        ),
    ]
